Muse-O/Backend

controllers/user.controller.js, routes/user.routes.js, services/user.service.js
[feat]회원가입시 이메일 인증번호 발송, joi email() 삭제
[chore]토큰 헤더 설정 프론트 요청사항 반영
=> Features/validate email [chore]토큰 헤더 설정 프론트 요청사항 반영

.gitignore, controllers/user.controller.js, routes/user.routes.js, services/user.service.js
[feat]회원가입시 이메일 인증번호검증 구현 및 이메일발송 수정
=> Features/validate email [feat]회원가입시 이메일 인증번호검증 구현 및 이메일발송 수정 #3

controllers/artgram.controller.js, repositories/artgram.repository.js, routes/artgram.routes.js, services/artgram.service.js
=> [fix]게시글 작성부분 img작성부분 오류수정#8

controllers/artgram.controller.js, services/artgram.service.js
=> [fix]이미지업로드fix#8

middlewares/multer.js
=> [fix]이미지작성#8

services/artgram.service.js
=> Revert "[fix]이미지업로드fix#8"

controllers/user.controller.js
[fix]팀장님과 소셜로그인 마지막 redirect 시 헤더/쿠키값 설정 변경한 내용 반영 #3
=> [fix]팀장님과 소셜로그인 마지막 redirect 시 헤더/쿠키값 설정 변경한 내용 반영 #3

controllers/mypage.controller.js, repositories/mypage.repository.js, routes/index.js, routes/mypage.routes.js, schemas/mypageReqSchema.js, services/mypage.service.js
[feat]마이페이지 프로필 조회 #33 프로필수정 #34
=> [feat]마이페이지 프로필 조회 #33 프로필수정 #34

controllers/mypage.controller.js, modules/parseModelToFlatObject.js, repositories/mypage.repository.js, routes/mypage.routes.js, services/mypage.service.js
[[feat]내가 작성한 전시글 조회] #35
[[feat] 내가 좋아요한 전시회 조회(좋아요 등록순)] #36 
[[fix] 내가 작성한 전시회 조회(작성순)] #35
[[feat]내가 스크랩한 전시회 조회(스크랩순)] #37 
[[feat]마이페이지 내가 작성한 아트그램 조회 현재 보류] #38
=> Features/mypage #35 #36 #37 #38

controllers/mypage.controller.js, controllers/notification.controller.js, controllers/user.controller.js, passport/google.js, passport/kakao.js, passport/naver.js, repositories/mypage.repository.js, repositories/notification.repository.js, repositories/user.repository.js, services/mypage.service.js, services/notification.service.js, services/user.service.js
=> [style]user,mypage,notification layer 프리티어 적용,jsdocs 추가

services/user.service.js
[[feat]access token 만료시간 연장] #4
=> [feat]access token 만료시간 연장#4

.vscode/extensions.json, __test__/artgram.routes..test.js, package-lock.json, package.json, repositories/search.repository.js, routes/admin.routes.js
아트그램 테스트코드 현재 미완성상태라 테스트시 오류가 발생해서 주석처리함
어드민 라우터생성
=> [fest]아트그램 테스트코드 주석처리.어드민 라우터 생성

repositories/artgram.repository.js, services/artgram.service.js, src/helpers/findAllUsers_helper.js
아트그램부분 조회/ 상세조회
변수이름 동사로 변경 
코드 리펙토링 일부
=> [fix]아트그램 리펙토링#237

repositories/artgram.repository.js
=> [fix]검색부분 충돌해결

controllers/exhibition.controller.js, repositories/exhibition.repository.js, schemas/pageQuerySchema.js, services/exhibition.service.js
전시 시작/종료 일, 어느 지역, 전시 태그, 전시 카테고리, 전시 제목 검색 필터링에 따른 목록 조회 기능 추가
=> [fix] 전시 목록 검색 필터링 기능 추가 #23

repositories/exhibitionReview.repository.js, repositories/mypage.repository.js, services/artgram.service.js, services/artgramComment.service.js, services/exhibition.service.js, services/exhibitionReview.service.js
#187 #35 #36 #37 #38 
- 마이페이지 슬라이더용 hasBackPage 추가
- 전시 리뷰 작성시 알림추가
- 본인에게는 알림 안오게
=> Features/mypage #187 #35 #36 #37 #38 

controllers/search.controller.js, models/artgramhashtag.js, repositories/search.repository.js, schemas/searchForInitial.js
태그검색 오후7시부터 새벽3시에 걸친 대장정이 마무리됏습니다...
뿌듯....
아트그램 태그검색이 된답니다..
=> [fix]태그검색 드디어완료...#120

controllers/search.controller.js, modules/searchArtgrams.js, repositories/search.repository.js, services/search.sevice.js
검색기능(각각의 타입값 추가)
아트그램 출력값추가
아트그램id
유저이메일, 프로필사진,닉네임
좋아요,스크랩,이미지 카운트
좋아요/스크랩 유무
아트그램1번째 이미지추가
전시회부분
이미지추가, 전시회id, 타이틀, 영문타이틀, 시작일-종료일
유저부분
type값 추가
=> [fix]검색기능 출력값변경#120 

controllers/search.controller.js, repositories/search.repository.js, services/search.sevice.js
유저가 검색후 저장한 타이틀 저장
로그인후 검색한 경우에만 저장가능하도록 설정
유저이메일값도 저장해서 최근검색어 저장
=> [fix]유저가 선택한 타이틀저장

controllers/search.controller.js, repositories/search.repository.js, services/search.sevice.js
=> Dev -> release 검색기록 로그인유저아닐시 저장X

controllers/search.controller.js, modules/searchArtgrams.js, repositories/search.repository.js, routes/search.routes.js, services/search.sevice.js
검색부분 레디스 데이터저장 시간변경
레디스 get주석해제
레디스 데이터에 들어있는 값때문에
프론트에서 못받아오는 에러발생
=> [fix]검색부분 레디스주석해제

controllers/admin.controller.js, controllers/search.controller.js, modules/searchArtgrams.js, repositories/search.repository.js, routes/admin.routes.js, test/fixtures/naver-users.fixtures.js, test/unit/controllers/admin.controller.test.js, test/unit/routes/admin.routes.test.js, test/unit/routes/search.routes.test.js
아트그램 검색부분
rows에서 태그검색부분이 추가되어있어서 해결함
=> [fix]아트그램검색부분 수정

repositories/search.repository.js, services/search.sevice.js
검색어가 없으면 아트그램 글이 원하지않는 상태에서도
들어가서 검색어값이 들어오지않으면
에러를 반환해줌
=> Dev -> release 검색어가 존재하지않으면 검색x

config/config.js, models/index.js, modules/sync-sequelize-model-testsync.js, package.json, repositories/admin.repository.js, services/admin.service.js, test/unit/controllers/admin.controller.test.js, test/unit/services/admin.service.test.js
아트그램 배열이 두개로 출력되는 에러가 발생해서
해결함
=> [fix]아트그램 검색기능에러해결#120

services/search.sevice.js
=> [fix]왜 배포만 하면 이상해지는것인가..? #120

repositories/search.repository.js
=> Dev -> release 레디스 캐싱수정

config/config.js, models/index.js, modules/searchArtgrams.js, package.json, repositories/search.repository.js, test/unit/repositories/admin.repository.test.js, test/unit/routes/admin.routes.test.js, test/unit/routes/artgram.routes.test.js, test/unit/services/admin.service.test.js
프론트에서 재사용가능하도록
imgUrl이 하나만 출력되도록 설정해줌
=> Dev -> release 아트그램검색시 imgUrl수정

repositories/search.repository.js
=> Dev -> release [fix]전시회 검색시 address값 포함

controllers/artgram.controller.js, modules/artgramModify.js, repositories/artgram.repository.js, routes/exhibition.routes.js, schemas/artgramReqSchema.js, services/artgram.service.js
아트그램 태그, 이미지 수정
태그값이 없을때도 동작하도록 구현
=> Dev -> release [fix]아트그램 수정부분 #9

controllers/admin.controller.js, controllers/artgram.controller.js, controllers/user.controller.js, modules/artgramModify.js, modules/findAdmin.js, repositories/admin.repository.js, repositories/search.repository.js, routes/admin.routes.js, routes/index.js, schemas/artgramModifyReqSchema.js, schemas/artgramReqSchema.js, services/admin.service.js, test/unit/controllers/admin.controller.test.js
=> [fix]아트그램 스키마변경

controllers/admin.controller.js, controllers/report.controller.js, models/articlereport.js, repositories/admin.repository.js, repositories/report.repository.js, services/admin.service.js, services/report.service.js
관리자페이지 
전시회승인리스트
전시회승인
신고리스트
신고
구현완료
=> [fix]관리자페이지 구현

modules/artgramModify.js, schemas/artgramModifyReqSchema.js, services/artgram.service.js
아트그램 수정시 이미지만 수정하고 싶어서
이미지만 바꿔서 보낼시
타이틀과 내용이 빈값으로 들어와서
에러가 발생
조이로 require설정을 해제 해주고
만약 빈값이 들어오면 수정이 되지않도록 변경해줌
=> [fix]아트그램 수정부분 타이틀,내용 undifined허용#9

modules/artgramModify.js, schemas/artgramModifyReqSchema.js, services/artgram.service.js
아트그램 수정부분
이미지만 수정시
타이틀과 내용이 빈값으로 들어와서
값이 존재하지않으면
수정되지않도록 설정
=> Dev -> release 아트그램 수정부분 에러

modules/artgramModify.js, services/artgram.service.js
원래 해시태그보다 값이 적거나 많아도 해시태그가 수정되도록설정해줌
=> [fix]아트그램 수정부분 해시태그fix#9

modules/artgramModify.js, schemas/artgramModifyReqSchema.js, services/artgram.service.js
아트그램 수정부분
db에 저장된 해시태그의 갯수보다
더 적거나 많은 값이 들어와도 수정되도록 설정.
=> Dev -> release 

controllers/admin.controller.js, controllers/mypage.controller.js, middlewares/authMiddleware_admin.js, repositories/admin.repository.js, repositories/mypage.repository.js, routes/admin.routes.js, routes/mypage.routes.js, services/admin.service.js, services/mypage.service.js
관리자페이지
- 작가 권한 승인
- 작가 승인 대기자 명단 조회
마이페이지
- 작가 승인대기로 상태 변경 api
=> 마이페이지, 관리자 페이지 작가 권한 관련 api 추가 

models/index.js, package-lock.json, package.json, routes/admin.routes.js, services/search.sevice.js, test/fixtures/admin.fixtures.js, test/unit/controllers/admin.controller.test.js, test/unit/routes/admin.routes.test.js, test/unit/server.js
어드민 라우터/ 컨트롤러 테스트 코드작성.
테스트코드 서버연결 모듈작성.
test/unit/server
const http = require("http");
const app = require("../../app");
const logger = require("../../middlewares/logger");
const server = http.createServer(app);
//0번 포트로 설정해 동적으로 포트가 실행되도록설정
//운영체제가 사용 가능한 포트를 자동할당.
server.listen(0, () => {
const address = server.address();
const port = typeof address === "string" ? address : address.port;
logger.info(`${port} 포트 번호로 서버가 실행되었습니다.`);
});
module.exports = server;
=> [feat]테스트코드 작성 #286

modules/searchArtgrams.js, repositories/search.repository.js
검색부분에서 redis로 캐싱하면 
실시간데이터인 좋아요, 스크랩부분이 반영되지않아서
삭제함.
추후에 연관검색어부분으로 레디스를 사용해볼예정
=> [fix]검색부분 레디스로 저장시 데이터의 일관성유지가 되지않는현상fix

repositories/search.repository.js
아트그램 좋아요, 스크랩 계속 실시간 반영이 되지않아서
롤백함
=> [fix]아트그램 검색 롤백#120

modules/searchArtgrams.js, repositories/search.repository.js
레디스부분을 삭제해도 좋아요와 스크랩부분이
실시간 반영되지않아서 롤백함
=> Dev -> release [fix]아트그램 검색 롤백

modules/searchArtgrams.js, repositories/search.repository.js
비회원시 스크랩과 좋아요가 출력되어서
제대로 반영이 되지않아서 수정함
=> [fix]비회원시 스크랩과 좋아요가 표시되서 fix함

modules/searchArtgrams.js, repositories/search.repository.js
아트그램 검색시 비회원일때도 liked, scrap출력되서 수정
=> Dev -> release [fix]아트그램 검색

repositories/search.repository.js
전시회도 비회원로그인시 
좋아요와 스크랩이 출력되고있어서 수정해줌
=> [fix]전시회검색

repositories/search.repository.js
현재 계속 전시회와 아트그램 좋아요와 스크랩이
정상적으로 출력되지않아서 코드 수정함
=> [fix]전시회 좋아요, 스크랩 코드변경

controllers/search.controller.js
콘솔로그로 토큰이 넘어오는지 확실하게 확인해보려고
추가함
=> 콘솔로그 추가로 서버에 토큰넘어오는지확인

controllers/websocket.cntroller.js, repositories/chat.repository.js, services/chat.service.js
=> [fix] 실시간 채팅 기능 코드 정리 #338

repositories/notification.repository.js
=> [fix]회원가입시 이메일토큰key명과 알림 streamkey 명이 겹쳐서 발생한 오류 수정 #3

app.js, middlewares/apiLogger.js, middlewares/logger.js, modules/counter.js, repositories/admin.repository.js
winston ,winston-daily-rotate-file, morgan 라이브러리 사용해서
각 API의 메서드별로 count되도록설정.
상세조회는 detail을 붙여서 따로 count 되도록 설정해줌.
추후에 스트레스테스트하는 Artillery라이브러리추가해서
api성능을 로깅하는 파일 구축예정
=> [feat]API출력횟수 로깅파일추가#384

app.js, middlewares/apiLogger.js, middlewares/logger.js, modules/counter.js, repositories/admin.repository.js, repositories/notification.repository.js, services/user.service.js
winston ,winston-daily-rotate-file, morgan 라이브러리 사용해서
각 API의 메서드별로 count되도록설정.
상세조회는 detail을 붙여서 따로 count 되도록 설정해줌.
추후에 스트레스테스트하는 Artillery라이브러리추가해서
api성능을 로깅하는 파일 구축예정
=> Dev -> release [feat]api출력횟수 로깅파일 추가

app.js, modules/counter.js, package-lock.json, package.json
=> [fix]api출력횟수 에러수정 #384

repositories/exhibition.repository.js, schemas/exhibitionReqSchema.js
=> [fix] 전시회 조회 쿼리 수정 #23

controllers/exhibition.controller.js, schemas/exhibitionReqSchema.js
온라인 전시의 경우 오픈/종료시간이 필수값이아님. 해당 내용 반영
=> [fix] 전시 등록시 오픈/종료 시간 검증 수정 #25

controllers/banner.controller.js, repositories/banner.repository.js
=> [fix]전시 조회 시 리뷰 평점 삭제된 리뷰도 반영된 것 변경

.github/workflows/release.yml
우선은 제 서버의 환경변수와 동일하게 작성해 뒀습니다.
만약 서버1번에서 아래의 터미널 실행환경이 다르다면 수정하시면 될것같습니다.
ssh -i private_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && git checkout release && git pull && npm install && pm2 delete 0 && pm2 start app.js"
=> [github Actions] 건님 서버 워크플로우 yml파일 작성 

app.js, controllers/user.controller.js
app.js x-powered-by헤더 제거, /api로 라우팅
[fix]usercontroller 쿠키 secure, httponly 적용
=> [fix] x-powered-by헤더 제거, /api로 라우팅, 쿠키 secure, httponly 적용

app.js
museoh vercel 기본 주소에서 museoh.art로 변경
=> [fix] app.js 로그코드 주석 처리 및 프록시 서버 주소 변경

app.js, middlewares/apiLogger.js
function incrementCounter(method, apiName) {
if (!counters[method][apiName]) {
counters[method][apiName] = 0;
}
counters[method][apiName]++;
}
function getCounter(apiName, method) {
return (counters[apiName] && counters[apiName][method]) || 0;
}
함수에서 받아오는 값이 반대로 설정되어있어서 제대로 반환을 하지못해서
함수 순서만 바꿔줌
method, apiName -> apiName, method
=> [fix]count증가 오류해결

app.js, config/config.js, models/index.js, modules/sync-sequelize-model-testsync.js, package-lock.json, package.json, test/scenarios.yaml
=> [feat]artillery파일 설정
